language: node_js
node_js:
  - "stable"
services:
  - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=01002f0e042c2d017dcc9ac9c6155276625b47fc38d2bd9f5f5ce1c49d3603eb
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
addons:
  code_climate:
    repo_token:
      secure: '01002f0e042c2d017dcc9ac9c6155276625b47fc38d2bd9f5f5ce1c49d3603eb'
script:
  - babel-node server.js &
  - npm run test
  - psql -c 'create database propertyprolitedb;' -U postgres
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
notifications:
  email: false
cache:
  directories:
    - "node_modules"
after_success: 
  - npm run coverage